/*Promise Middleware creates _SUCCESS or _FAILURE*/

export const CREATE_POST_DUPLICATE = 'CREATE_POST_DUPLICATE';
export const POST_INCREMENT_COUNT = 'POST_INCREMENT_COUNT';
export const DESTROY_POST = 'DESTROY_POST';
export const POST_TYPING = 'POST_TYPING';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_DUPLICATE = 'CREATE_COMMENT_DUPLICATE';
export const COMMENT_INCREMENT_COUNT = 'COMMENT_INCREMENT_COUNT';
export const DESTROY_COMMENT = 'DESTROY_COMMENT';
export const COMMENT_TYPING = 'TYPING';

export const LOCAL_LOGIN_USER_START = 'LOCAL_LOGIN_USER_START';
export const LOCAL_LOGIN_FORM_UPDATE = 'LOCAL_LOGIN_FORM_UPDATE';
export const LOCAL_LOGIN_SUCCESS_USER = 'LOCAL_LOGIN_SUCCESS_USER';
export const LOCAL_LOGIN_ERROR_USER = 'LOCAL_LOGIN_ERROR_USER';

export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_START_USER = 'SIGNUP_START_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const SIGNUP_ERROR_USERNAME_EMTPY = 'SIGNUP_ERROR_USERNAME_EMTPY';
export const SIGNUP_UPDATE_USER = 'SIGNUP_UPDATE_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const EMAIL_SIGNUP_START       = "EMAIL_SIGNUP_START";
export const EMAIL_SIGNUP_COMPLETE    = "EMAIL_SIGNUP_COMPLETE";
export const EMAIL_SIGNUP_ERROR       = "EMAIL_SIGNUP_ERROR";
export const EMAIL_SIGNUP_FORM_UPDATE = "EMAIL_SIGNUP_FORM_UPDATE";

export const CLEAR_LOGIN_DIALOGS = 'CLEAR_LOGIN_DIALOGS';


export const POST_CLEAR_STATE = 'POST_CLEAR_STATE';
export const POSTS_LOAD_REQUEST = 'POSTS_LOAD_REQUEST';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const POSTS_GET = 'POSTS_GET';
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS';
export const POSTS_GET_FAILURE = 'POSTS_GET_FAILURE';
export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST';

export const SELECT_PORT = 'SELECT_PORT';
export const INVALIDATE_PORT = 'INVALIDATE_PORT';
  
export const POSTS_VOTE = 'POSTS_VOTE';
export const POSTS_UNVOTE = 'POSTS_UNVOTE';
export const POSTS_VOTE_REQUEST = 'POSTS_VOTE_REQUEST';
export const POSTS_UNVOTE_REQUEST = 'POSTS_UNVOTE_REQUEST';
export const POSTS_VOTE_SUCCESS = 'POSTS_VOTE_SUCCESS';
export const POSTS_UNVOTE_SUCCESS = 'POSTS_UNVOTE_SUCCESS';

export const POSTS_SAVE = 'POSTS_SAVE';
export const POSTS_UNSAVE = 'POSTS_UNSAVE';
export const POSTS_SAVE_REQUEST = 'POSTS_SAVE_REQUEST';
export const POSTS_UNSAVE_REQUEST = 'POSTS_UNSAVE_REQUEST';
export const POSTS_SAVE_SUCCESS = 'POSTS_SAVE_SUCCESS';
export const POSTS_UNSAVE_SUCCESS = 'POSTS_UNSAVE_SUCCESS';

export const POSTS_DELETE = 'POSTS_DELETE';
export const POSTS_DELETE_REQUEST = 'POSTS_DELETE_REQUEST';
export const POSTS_DELETE_SUCCESS = 'POSTS_DELETE_SUCCESS';
export const POSTS_DELETE_FAILURE = 'POSTS_DELETE_FAILURE';

export const POST_GET = 'POST_GET';
export const POST_GET_SUCCESS = 'POST_GET_SUCCESS';